SUMMARY = "TensorFlow is an open source software library for numerical computation using data flow graphs"
LICENSE = "Apache-2.0"

SRC_URI = "https://files.pythonhosted.org/packages/36/3a/59e68f1ece4eaa73726efebd8ba82b4b59ce31e2d69136297c8d81764892/tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl"
SRC_URI[md5sum] = "cabf7019806f89c1ed51be3cf619ecbc"
SRC_URI[sha256sum] = "b680435e7fe7d1c977bd9dcc6d18edaee230fef40c37a4dc3a0ecb65ac2b9087"
